[project]
name = "FRC-2026"
version = "1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
    "robotpy[navx,pathplannerlib,phoenix6,rev]==2025.3.2.2",
    "photonlibpy",
]


[tool.uv]
python-preference = "managed"
